export const SET_COURSES = 'SET_COURSES';
export const SET_USER = 'SET_USER';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const RESET_APP = 'RESET_APP';

export const TOGGLE_REQUEST = 'TOGGLE_REQUEST';
export const TOGGLE_UPLOAD = 'TOGGLE_UPLOAD';
export const OPEN_SEARCH = 'OPEN_SEARCH';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const TOGGLE_SHOWMORE = 'TOGGLE_SHOWMORE';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const TOGGLE_USERMENU = 'TOGGLE_USERMENU';
export const CLOSE_USERMENU = 'CLOSE_USERMENU';
export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const ADD_COURSES = 'ADD_COURSES';
export const SWITCH_ACTIVE_DEPARTMENT = 'SWITCH_ACTIVE_DEPARTMENT';
export const SWITCH_ACTIVE_COURSE = 'SWITCH_ACTIVE_COURSE';
export const SET_FILETYPE = 'SET_FILETYPE';
export const SWITCH_ACTIVE_MYCOURSE = 'SWITCH_ACTIVE_MYCOURSE';
export const SET_MYCOURSE_FILETYPE = 'SET_MYCOURSE_FILETYPE';
export const RESET_ACTIVES = 'RESET_ACTIVES';
export const SET_ERROR = 'SET_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const ADD_NEW_NOTIFICATION = 'ADD_NEW_NOTIFICATION';

export const SWITCH_MAIN_MENU = 'SWITCH_MAIN_MENU';
export const SWITCH_SUB_MENU = 'SWITCH_SUB_MENU';
export const SWITCH_TAB = 'SWITCH_TAB';
export const SET_TABLE_DATA = 'SET_TABLE_DATA';
export const RESET_ADMIN_MENU = 'RESET_ADMIN_MENU';
export const TOGGLE_ADMIN_LOADER = 'TOGGLE_ADMIN_LOADER';
