export const SET_COURSES = "SET_COURSES";
export const SET_USER = "SET_USER";
export const RESET_APP = "RESET_APP";

export const TOGGLE_REQUEST = "TOGGLE_REQUEST";
export const TOGGLE_UPLOAD = "TOGGLE_UPLOAD";
export const OPEN_SEARCH = "OPEN_SEARCH";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const TOGGLE_SHOWMORE = "TOGGLE_SHOWMORE";
export const SEARCH_RESULTS = "SEARCH_RESULTS";
export const TOGGLE_USERMENU = "TOGGLE_USERMENU";
export const TOGGLE_NOTIFICATIONS = "TOGGLE_NOTIFICATIONS";
export const CLOSE_MODAL = "CLOSE_MODAL";
