name: Lint Test
on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.6.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        npm install
        npm i eslint
    - name: Run lint test
      run: |
        npm run lint
